In [12]:
import torch
data1 = torch.rand(2,3)
data2 = torch.rand(2,3)
out2 = [data1, data2]
out2

[tensor([[0.9438, 0.5266, 0.9796],
         [0.6996, 0.8280, 0.4730]]),
 tensor([[0.0375, 0.5305, 0.7122],
         [0.3722, 0.3672, 0.9000]])]

In [19]:
# def test(out):
#     return *out

a, b = out2
a

tensor([[0.9438, 0.5266, 0.9796],
        [0.6996, 0.8280, 0.4730]])

In [16]:
print(*out2)

tensor([[0.9438, 0.5266, 0.9796],
        [0.6996, 0.8280, 0.4730]]) tensor([[0.0375, 0.5305, 0.7122],
        [0.3722, 0.3672, 0.9000]])


In [29]:
data = torch.arange(36).reshape(2,3,6)
torch.chunk(data, 2, dim=2)

(tensor([[[ 0,  1,  2],
          [ 6,  7,  8],
          [12, 13, 14]],
 
         [[18, 19, 20],
          [24, 25, 26],
          [30, 31, 32]]]),
 tensor([[[ 3,  4,  5],
          [ 9, 10, 11],
          [15, 16, 17]],
 
         [[21, 22, 23],
          [27, 28, 29],
          [33, 34, 35]]]))

In [28]:
data

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]])